<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cash Disbursement</name>
   <tag></tag>
   <elementGuidId>5c6b8f4a-1efb-4818-a94a-b5a4db31e4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Reportid1']/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62cbc5d6-630e-49bc-bd1b-eea99805f10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Cash_Disbursement.jsp</value>
      <webElementGuid>972c439e-a758-4bd7-950d-4ce8ab5191d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cash Disbursement</value>
      <webElementGuid>a6ea24bb-cedf-41a0-8c38-190e79369dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reportid1&quot;)/li[6]/a[1]</value>
      <webElementGuid>905bb8be-d51f-494a-8d0e-e4f5ba9485da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Reportid1']/li[6]/a</value>
      <webElementGuid>93671a06-37c2-47ee-904e-fd3f55d64795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cash Disbursement')]</value>
      <webElementGuid>fb64eb1a-ae35-4cd5-99cd-34372b099ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Receipts'])[1]/following::a[1]</value>
      <webElementGuid>488e309d-3a02-4b14-9c4a-60691caa345c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Journal'])[1]/following::a[2]</value>
      <webElementGuid>04841759-7d8f-464b-8b59-f1fd5fb27e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsidiary Ledger'])[1]/preceding::a[1]</value>
      <webElementGuid>7b1e3f77-98ec-4ed5-a781-b253cde93cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR Summary'])[1]/preceding::a[2]</value>
      <webElementGuid>31c7abcd-e7f8-434c-b847-f02496337b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cash Disbursement']/parent::*</value>
      <webElementGuid>3f719309-baf7-41f9-9380-b236fb57acb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Cash_Disbursement.jsp')]</value>
      <webElementGuid>577d7a8e-d115-4e3c-8667-c336c057270d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>c0072c76-2444-4eb4-8436-a9a7274cb2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Cash_Disbursement.jsp' and (text() = 'Cash Disbursement' or . = 'Cash Disbursement')]</value>
      <webElementGuid>d5258e59-b9c4-4bc5-9415-8709c0f41c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
