<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Sign In_passWord</name>
   <tag></tag>
   <elementGuidId>5e3f72b2-3924-448c-adf0-825fba94c210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passWord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passWord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6168a08-1f22-4fe6-ab29-3566ab8f7b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f6a2940f-5fec-473c-a9ab-fb7c28c5b814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>74c3ea47-8e53-40ee-8add-80a3469acd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passWord</value>
      <webElementGuid>be414aba-84a6-44b7-8d4d-240641d96510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a072e93b-3a06-4696-a137-6e8e4824334f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passWord&quot;)</value>
      <webElementGuid>21e224c0-ec80-4580-a0c0-8aaca84cb5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passWord']</value>
      <webElementGuid>b2da9230-9014-414c-ae36-5c966ecbec34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>43ddcc8d-3f89-4a4c-a17d-bc7122241b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @id = 'passWord' and @type = 'password']</value>
      <webElementGuid>7fc585eb-1125-4898-992b-6973b6a98c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
