<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adjusting Entries</name>
   <tag></tag>
   <elementGuidId>1b41e59f-0efd-448b-a5e6-57d7da838a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Report2 > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Report2']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9a42546-38de-4934-8989-d1dca6104d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Adjusting_Entries.jsp</value>
      <webElementGuid>bf29955a-d35d-43a3-91a0-1d16882b1f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adjusting Entries</value>
      <webElementGuid>d429ae27-78a9-4a6a-a8f2-0faca75a93f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Report2&quot;)/li[4]/a[1]</value>
      <webElementGuid>560fc49f-5768-41f1-aaec-d89a490c5455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Report2']/li[4]/a</value>
      <webElementGuid>c1b22224-14fe-4eb2-ae63-20e66979a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Adjusting Entries')]</value>
      <webElementGuid>6cf42f7e-fa01-439f-9753-889fa3004918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance Sheet'])[1]/following::a[1]</value>
      <webElementGuid>a0f6f4c0-2f51-4546-a761-aa9775b6119a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Statement'])[1]/following::a[2]</value>
      <webElementGuid>51853d33-a189-4c8b-bbdd-b5685ffe5b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Manual Entries'])[1]/preceding::a[1]</value>
      <webElementGuid>9e67980d-d664-42a1-8d98-bc517d13f683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidated FS'])[1]/preceding::a[2]</value>
      <webElementGuid>49e964a2-3492-4624-81af-75177713a1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adjusting Entries']/parent::*</value>
      <webElementGuid>aba1c141-9a0c-4e40-958b-eb9929b505b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Adjusting_Entries.jsp')]</value>
      <webElementGuid>12b9738a-dbfb-4c27-aeb1-ccb08a50fbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li[4]/a</value>
      <webElementGuid>9db3374c-342b-4132-ac86-2f7258889740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Adjusting_Entries.jsp' and (text() = 'Adjusting Entries' or . = 'Adjusting Entries')]</value>
      <webElementGuid>ed271780-830f-407c-87b1-c93bbff981ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
