<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_HEAD OFFICE</name>
   <tag></tag>
   <elementGuidId>10eca1d1-0feb-4329-ad5d-ff78b2d1a6e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='WelcomeLabel']/b[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>63f21e75-97e1-4a22-ba9f-8441362233b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HEAD OFFICE</value>
      <webElementGuid>52532dea-8a0d-44e1-9179-782a50c9beec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WelcomeLabel&quot;)/b[2]</value>
      <webElementGuid>a33162d9-3d9a-4422-948e-ed375cdbed96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='WelcomeLabel']/b[2]</value>
      <webElementGuid>518f1100-5717-4434-9794-17a2dcaa6df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::b[1]</value>
      <webElementGuid>d7742bde-4faf-422a-a083-a4b7153088b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Transaction'])[1]/preceding::b[1]</value>
      <webElementGuid>da1bc88a-31d5-45a9-a992-dbbd8aef68cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Transaction'])[1]/preceding::b[1]</value>
      <webElementGuid>884cb4f8-dba1-4394-9cf1-a81e68a5bebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HEAD OFFICE']/parent::*</value>
      <webElementGuid>2a391d99-c3aa-47ce-9da9-a39dba9776d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b[2]</value>
      <webElementGuid>0cfd2427-e16b-4522-8fa8-2edd1b357a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'HEAD OFFICE' or . = 'HEAD OFFICE')]</value>
      <webElementGuid>6a70e483-18f1-49e6-a087-314b04cefe36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
