<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_btnPDFAdj</name>
   <tag></tag>
   <elementGuidId>46f926bf-a3f6-4f6c-86d4-52f78c817a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPDFAdj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnPDFAdj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84f85a01-fe44-4092-b4c7-277810054659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d397847c-03a1-49bd-8f82-5852bc5b2e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPDFAdj</value>
      <webElementGuid>3d596a93-9026-4457-aec3-f556a93a979f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>4537a933-b9a2-4a52-b101-eb5263d960be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View PDF</value>
      <webElementGuid>ba796178-dcf9-4eac-b277-d31404ade26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPDFAdj&quot;)</value>
      <webElementGuid>6285a008-3bf0-46a9-ad60-648e21a0e903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnPDFAdj']</value>
      <webElementGuid>6b93cfcc-bcf9-4ff2-954b-fd479588a8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/div[2]/input[2]</value>
      <webElementGuid>dca79c54-0d6a-405a-aa17-2c8a2e646cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>be5a8b55-eff2-4ec5-ab7f-c88906a65fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnPDFAdj']</value>
      <webElementGuid>20ae3b46-4954-41c2-9f06-f3003d8cbef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
