<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select Item---JanuaryFebruaryMarc_7b8eaa</name>
   <tag></tag>
   <elementGuidId>74ac011a-61c8-4977-9650-64148aea9cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3b7223d-00ad-466b-ae4d-dd44aa6e0b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboMonth</value>
      <webElementGuid>3b4f5b96-80a5-4463-92f5-f3ce89fc1094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>a660463a-402b-4610-8087-0221293c2ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										---Select Item---
										January
										February
										March
										April
										May
										June
										July
										August
										September
										October
										November
										December
										
									</value>
      <webElementGuid>9acb5891-6141-4ba9-bf98-f1e681661a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboMonth&quot;)</value>
      <webElementGuid>3f4ca5ee-b41d-48ac-820c-d5578625dc9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboMonth']</value>
      <webElementGuid>79383cf8-4323-4456-bb8c-58543e08ea49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/div/div[5]/select</value>
      <webElementGuid>536fb6d2-a91e-40c6-ab51-c4b0c0cdb894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/following::select[1]</value>
      <webElementGuid>617a7196-a8dd-4c7e-87a8-1d593301c2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[1]/following::select[2]</value>
      <webElementGuid>e03784ff-f101-4828-a176-7969ee73abe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/preceding::select[1]</value>
      <webElementGuid>16e6a7c6-5185-49de-ab09-2b52825859b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait. DO NOT close your browser.'])[1]/preceding::select[2]</value>
      <webElementGuid>72749b1c-cba7-4fcb-a8bc-bdd8b0933d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>61f63cbc-6c2c-40d5-8ff2-88bf3cafcfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboMonth' and (text() = '
										---Select Item---
										January
										February
										March
										April
										May
										June
										July
										August
										September
										October
										November
										December
										
									' or . = '
										---Select Item---
										January
										February
										March
										April
										May
										June
										July
										August
										September
										October
										November
										December
										
									')]</value>
      <webElementGuid>9ee1ab6d-c682-4c8d-b117-cebe0490bab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
