<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_General Ledger</name>
   <tag></tag>
   <elementGuidId>bdf07e84-a04c-4a98-8756-6de526a1ea87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='DashboardHeader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DashboardHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a17848e2-bfdc-4077-8a63-b98b05b6c352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-header</value>
      <webElementGuid>33dd53ab-efb3-43c1-8e86-ea5d5d82fae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DashboardHeader</value>
      <webElementGuid>9e5f0b8d-2ad0-49a6-a9a8-5f014220d959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General Ledger</value>
      <webElementGuid>9ca501cf-1e78-451b-b20a-30dc0c4e529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DashboardHeader&quot;)</value>
      <webElementGuid>1930e8ec-d162-450d-8cfc-1fed33ca5871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='DashboardHeader']</value>
      <webElementGuid>ebb987f9-36d7-4cd7-b997-d6fb88b92e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/h1</value>
      <webElementGuid>fb9c8e97-deba-4498-b775-f5fcbbf378dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Areas'])[1]/following::h1[1]</value>
      <webElementGuid>046c8a6b-33c2-4574-8aa4-4c6347ba8958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Parameters'])[1]/following::h1[1]</value>
      <webElementGuid>6e7d9d08-8821-4d68-b294-884db857f643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Type'])[1]/preceding::h1[1]</value>
      <webElementGuid>8ae6dc62-d78d-4000-97d1-0ef162ad31eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/preceding::h1[1]</value>
      <webElementGuid>430ed694-c418-494e-94f2-ead89a950a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>810f9b18-8c4f-428d-893d-b7b3a81645da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'DashboardHeader' and (text() = 'General Ledger' or . = 'General Ledger')]</value>
      <webElementGuid>4dfbb5bc-1a34-4bbd-9c96-9e526349f0a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
