<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Balance Sheet</name>
   <tag></tag>
   <elementGuidId>6d34b389-b6ce-4302-991e-ff469002dceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Report2 > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Report2']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6bfd11d0-1214-4afb-ba6f-8b3113dfb9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Balance_Sheet.jsp</value>
      <webElementGuid>47b1fea4-e16e-4393-abb6-d5576c481757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Balance Sheet</value>
      <webElementGuid>1ac92afb-fc7b-464a-a7d8-5ac39ed9001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Report2&quot;)/li[3]/a[1]</value>
      <webElementGuid>3f54b084-0211-4e38-bab6-e05a45037b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Report2']/li[3]/a</value>
      <webElementGuid>08902a7e-24c4-4a6c-a8d0-ffe283453e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Balance Sheet')]</value>
      <webElementGuid>5030658c-a550-4cbf-b152-50c6700aaaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Statement'])[1]/following::a[1]</value>
      <webElementGuid>bbdb21aa-554e-4f92-80cf-ae9b0745b530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trial Balance Report'])[1]/following::a[2]</value>
      <webElementGuid>ed9735e5-df30-4713-a396-12543af362ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjusting Entries'])[1]/preceding::a[1]</value>
      <webElementGuid>7ff4e189-3ced-4875-b267-7bdbb9f0214b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Manual Entries'])[1]/preceding::a[2]</value>
      <webElementGuid>200df61b-1712-4a71-be21-89eb2e3fc4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Balance Sheet']/parent::*</value>
      <webElementGuid>d263201a-d797-44c3-ac04-f76de0c683de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Balance_Sheet.jsp')]</value>
      <webElementGuid>a46e57b4-2066-4322-8cc2-84c456d62da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>9accdf79-fcf6-4e62-8030-b5caa2009403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Balance_Sheet.jsp' and (text() = 'Balance Sheet' or . = 'Balance Sheet')]</value>
      <webElementGuid>a96d1fd8-b70d-4bde-8030-09b1e523714d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
