<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_btnPDFBS</name>
   <tag></tag>
   <elementGuidId>221e4444-e980-49ef-9e7c-9b0a5270e8cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPDFBS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnPDFBS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0ffa35b-36f4-4996-a3f0-ab3d68b934ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68cf8c64-c2b2-4373-821d-5f62aaeb2ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPDFBS</value>
      <webElementGuid>4debc26f-13de-4489-b807-db2d45505542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>23a67a47-dafb-4d09-9967-d219a6e1ee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View PDF</value>
      <webElementGuid>5eb4098c-68ce-4e50-b08f-7f9b810943cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPDFBS&quot;)</value>
      <webElementGuid>e41fe737-eb89-49c8-9e79-9c7570dc6a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnPDFBS']</value>
      <webElementGuid>8477014e-d480-4fb1-b7f6-16a7838fa51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/div[2]/input[2]</value>
      <webElementGuid>53a7a9d1-642c-4729-88a0-ea180ebc557d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>8b9a41d4-9385-4d57-a2e2-9ff1ad1bac85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnPDFBS']</value>
      <webElementGuid>237a4f05-2523-4f99-b407-71a8a340e91d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
