<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Trial Balance Report</name>
   <tag></tag>
   <elementGuidId>eb1ef0fe-5523-47d3-aac9-9044c5072157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Report2 > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Report2']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dbb8a77-130c-4322-ad5f-ff5ec4c0b2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Trial_Balance.jsp</value>
      <webElementGuid>f68432a3-739d-488b-9687-bcce0c761450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trial Balance Report</value>
      <webElementGuid>b21dd5a2-6762-468c-9d6a-cb416d53e2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Report2&quot;)/li[1]/a[1]</value>
      <webElementGuid>0f8c546c-6a3f-46d5-b088-8b5de6bd7d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Report2']/li/a</value>
      <webElementGuid>bfcc8fd8-a573-4b35-ac82-ac8fb262606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Trial Balance Report')]</value>
      <webElementGuid>5e65c2ab-6ee8-4548-8df9-98dae1806e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Reports'])[1]/following::a[1]</value>
      <webElementGuid>948cccd3-9355-42bf-9669-2059268c7395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR Summary'])[1]/following::a[2]</value>
      <webElementGuid>e81be2f5-5f65-4d99-a2f6-5520a8db369e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Statement'])[1]/preceding::a[1]</value>
      <webElementGuid>1bf3aeae-e937-4944-937f-e3d7e6c774a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance Sheet'])[1]/preceding::a[2]</value>
      <webElementGuid>f56593e4-2455-4737-8080-456a9443f24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Trial Balance Report']/parent::*</value>
      <webElementGuid>a0393dad-73bd-4fbe-9953-7f1094975059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Trial_Balance.jsp')]</value>
      <webElementGuid>9905a568-98d1-45d3-8f0e-38f950e3aead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li/a</value>
      <webElementGuid>6dde0fa0-1d63-43f8-be22-bc46f9371f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Trial_Balance.jsp' and (text() = 'Trial Balance Report' or . = 'Trial Balance Report')]</value>
      <webElementGuid>f6e2a8a7-06ad-450b-a920-5b1a07fad001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
