<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_btnPDFTB</name>
   <tag></tag>
   <elementGuidId>bc1d50e9-d719-466e-ac55-e3442dc56af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPDFTB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnPDFTB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97239490-7fcf-4011-92c1-d9d31c7f755c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c64df7ba-6877-4a53-9095-ca2b8496a3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPDFTB</value>
      <webElementGuid>32c570e0-fe74-428f-b5a5-8a734e289533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>32e1a887-8cd3-4cec-a8f9-1c579887f3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View PDF</value>
      <webElementGuid>8202d660-1baf-4bca-bc69-fc8a16cc182c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPDFTB&quot;)</value>
      <webElementGuid>b8cf3c37-3a57-4a0b-9d43-b4b89d04811c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnPDFTB']</value>
      <webElementGuid>aa518c9c-8da4-49cb-accf-6e64a53020c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/div[2]/input[2]</value>
      <webElementGuid>a798bb6b-317d-4455-b7fe-37d11aaeaea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>9664e418-5eba-4386-ab9c-878e3cac6372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnPDFTB']</value>
      <webElementGuid>3d6e977b-d9b5-4b81-a6cd-6e3e5c5a0bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
