<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OR Summary</name>
   <tag></tag>
   <elementGuidId>a7cb0eb6-ee1f-41f2-9a41-9fcaef1348e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Reportid1']/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38306369-91b1-437b-ab18-04e8664f8cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ORSummary.jsp</value>
      <webElementGuid>70e64ddf-384a-4e52-8f3a-adb615663973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OR Summary</value>
      <webElementGuid>83972799-3243-4827-894c-13957d351e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reportid1&quot;)/li[8]/a[1]</value>
      <webElementGuid>84115bde-83b7-4308-a074-98f15f3349d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Reportid1']/li[8]/a</value>
      <webElementGuid>871e5680-4eb8-4ff7-9b2f-fae10e066b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OR Summary')]</value>
      <webElementGuid>e6a0a18a-a8e9-4793-89b8-622d093b32c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsidiary Ledger'])[1]/following::a[1]</value>
      <webElementGuid>f4c9c6e1-702d-4f2b-9304-f1e9949b6adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Disbursement'])[1]/following::a[2]</value>
      <webElementGuid>783c05de-2dbc-430e-8c3f-1a3eba6dc623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Reports'])[1]/preceding::a[1]</value>
      <webElementGuid>ee174472-262c-4b66-985a-1a9eb31083bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trial Balance Report'])[1]/preceding::a[2]</value>
      <webElementGuid>d2095390-cbe5-4f26-8c10-ec803ce0bab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OR Summary']/parent::*</value>
      <webElementGuid>5d70c81a-bfdc-451e-81f1-7f307793ecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ORSummary.jsp')]</value>
      <webElementGuid>2a592aba-dc0d-4040-af56-a6402d472e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>1795029a-1bf9-44b4-b4d3-e039ddd25f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ORSummary.jsp' and (text() = 'OR Summary' or . = 'OR Summary')]</value>
      <webElementGuid>c1575063-d85f-4933-909d-a4119c31e511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
