<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Sign In_passWord</name>
   <tag></tag>
   <elementGuidId>aca47b2e-1063-476c-8981-30369d7a0c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passWord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passWord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84d4f021-5dda-4808-b6e0-0765233edffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f644e36c-db30-485c-8ca3-ec061c1a5e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>894f90be-404e-4412-b6a4-b951d006b1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passWord</value>
      <webElementGuid>ba2b288a-8916-42bd-9c4a-db3593453e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9b448484-cd62-404e-babf-e2602c4d5d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passWord&quot;)</value>
      <webElementGuid>6bdfab23-46de-4043-80b9-2293bf7c0886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passWord']</value>
      <webElementGuid>adaf3773-4b83-4cdd-8d44-457b6b2e2caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cdf2544d-4ecd-46ed-b237-35bd0376202d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @id = 'passWord' and @type = 'password']</value>
      <webElementGuid>a4f6635c-672b-4d12-941e-98d33d0fd70b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
