<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_btnPDFOR</name>
   <tag></tag>
   <elementGuidId>36b208db-4d79-4c0d-9bfc-6bf1adcb20af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnPDFOR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnPDFOR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74997dda-6cb7-45b6-8e5f-c192ac39db00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce5738f2-5d87-4e5c-966e-f09b44a615ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPDFOR</value>
      <webElementGuid>ad4b6532-28ef-42fd-8c97-0c90d3e1aed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>e7d8fcd9-acd0-4d15-8643-f130b2985dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View PDF</value>
      <webElementGuid>aa5ac06e-f061-40c5-951b-0308231e342f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPDFOR&quot;)</value>
      <webElementGuid>d610d78c-7dac-4f3e-877c-5a22188d7994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnPDFOR']</value>
      <webElementGuid>49f21998-e882-44a3-bcdd-9fe8d773a282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/div/div[2]/input[2]</value>
      <webElementGuid>b32d4c67-1ba4-4dbe-9fa4-f7b44482e607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>7ab1ba90-e87f-4bc6-8798-39d8d30c8ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnPDFOR']</value>
      <webElementGuid>e6d4a39f-d2cd-4e78-9710-dfd8707e6dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
