<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sales Journal</name>
   <tag></tag>
   <elementGuidId>d07cb9e7-ebf3-4d7e-b861-713c21c4f228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Reportid1']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Reportid1 > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3df47cef-ebc0-4dd1-8aba-01da1720537c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>salesjournal.jsp</value>
      <webElementGuid>4316981d-d21b-4792-b7a6-81e615f64c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales Journal</value>
      <webElementGuid>803ed88b-0cfa-4cfc-a5fa-98ab2434097d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reportid1&quot;)/li[3]/a[1]</value>
      <webElementGuid>2044f93c-200a-499b-b6f6-bbf9c8c255b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Reportid1']/li[3]/a</value>
      <webElementGuid>ad65a620-3867-4fe4-8ad1-6901c64bc004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sales Journal')]</value>
      <webElementGuid>19d2d3b2-f972-465a-b7d6-a28e71db60fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Journal'])[1]/following::a[1]</value>
      <webElementGuid>91c49161-9e83-470a-b60d-5b52887dd666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Ledger'])[1]/following::a[2]</value>
      <webElementGuid>8a20d96d-76db-4015-8c20-2b8a5cae6e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Journal'])[1]/preceding::a[1]</value>
      <webElementGuid>25f6fd66-e9bc-4725-b12b-33a6a167f46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Receipts'])[1]/preceding::a[2]</value>
      <webElementGuid>15766270-7af1-4933-b418-19f5727a856c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales Journal']/parent::*</value>
      <webElementGuid>9391a7c5-4df7-4ff5-adea-f675521a1f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'salesjournal.jsp')]</value>
      <webElementGuid>b7ec8eee-13d7-4ce5-8f52-297fef0b0be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul/li[3]/a</value>
      <webElementGuid>1092b626-e234-4e3d-a44d-03b4673a29de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'salesjournal.jsp' and (text() = 'Sales Journal' or . = 'Sales Journal')]</value>
      <webElementGuid>368da2c8-885b-4458-85d0-52b076de41dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
